steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/tradingagents-crypto:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/tradingagents-crypto:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tradingagents-crypto:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tradingagents-crypto:latest']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'tradingagents-crypto',
      '--image', 'gcr.io/$PROJECT_ID/tradingagents-crypto:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '2Gi',
      '--cpu', '2',
      '--timeout', '3600',
      '--concurrency', '10',
      '--port', '8080',
      '--set-env-vars', 'ENVIRONMENT=production'
    ]

images:
  - 'gcr.io/$PROJECT_ID/tradingagents-crypto:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/tradingagents-crypto:latest'

timeout: '1200s'

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100' 